### ISSUE TITLE
Not detecting AMD GPUs

### ISSUE THREAD

**Issue by sizhuk** [nicehash/NiceHashMiner-Archived#256] opened 2016-09-26 18:01 UTC
I have two computers with the same problem with a little difference. I connect to it using Teamviewer.
The first one has 4xRadeon 6870
The second: 1xRadeon 6870 and 2x Radeon 7790
some lines from log:

```
[2016-09-26 20:49:37] [INFO] [ComputeDeviceQueryManager] 
QueryVideoControllers: 
    Win32_VideoController detected:
        Name AMD Radeon HD 6800 Series
        Description AMD Radeon HD 6800 Series
        PNPDeviceID PCI\VEN_1002&DEV_6738&SUBSYS_23051787&REV_00\4&247F140C&0&0028
        DriverVersion 15.200.1062.1004
        Status OK
[2016-09-26 19:39:22] [INFO] [ComputeDeviceQueryManager] AMD GPUs count is 0
[2016-09-26 19:39:22] [INFO] [ComputeDeviceQueryManager] Cuda NVIDIA/CUDA device count GOOD
[2016-09-26 19:39:22] [INFO] [ComputeDeviceQueryManager] AMD GPU device count BAD!!!
```

On the second PC first run gives the same result in log, it shows in list only processor. But when I close the program and re-run it GPUs are detected and there is a line from log.
`[2016-09-26 20:51:40] [INFO] [ComputeDeviceQueryManager] AMD GPU device count GOOD`
Doing the same thing dont help on the first PC.
Catalyst 15.7, Windows 7x64. No monitors attached to cards.
Version 1.6.1.1 detects it without any problems, but i'd like to use the new version, because it gives me possibility to mine with per device settings and algorithms. I see, that in 1.7 versions gpu detector is the separate file, not like it was in the previous branch. Maybe this issue caused by changes in detecting algorithm and videocards can't pass the all the new checks.

**Comment by S74nk0** [comment] 2016-10-03 17:48
Hi @sizhuk. The issue is in the new way NHM is detecting AMD and NVIDIA cards. We will take a look into this.

**Comment by jane1e** [comment] 2016-10-29 18:07
Same for me 2x 7900 + 2x R9 390

QueryVideoControllers: 
    Win32_VideoController detected:
        Name AMD Radeon HD 7900 Series
        Description AMD Radeon HD 7900 Series
        PNPDeviceID PCI\VEN_1002&DEV_679A&SUBSYS_254C1458&REV_00\4&2543D5D&0&00E3
        DriverVersion 15.300.1025.1001
        Status OK
    Win32_VideoController detected:
        Name AMD Radeon HD 7900 Series
        Description AMD Radeon HD 7900 Series
        PNPDeviceID PCI\VEN_1002&DEV_679A&SUBSYS_254C1458&REV_00\4&C9C687&0&0009
        DriverVersion 15.300.1025.1001
        Status OK
    Win32_VideoController detected:
        Name AMD Radeon (TM) R9 390 Series
        Description AMD Radeon (TM) R9 390 Series
        PNPDeviceID PCI\VEN_1002&DEV_67B1&SUBSYS_22BD1458&REV_80\4&20BDBE28&0&00E0
        DriverVersion 15.300.1025.1001
        Status OK
    Win32_VideoController detected:
        Name AMD Radeon (TM) R9 390 Series
        Description AMD Radeon (TM) R9 390 Series
        PNPDeviceID PCI\VEN_1002&DEV_67B1&SUBSYS_22BD1458&REV_80\4&BAB4994&0&0008
        DriverVersion 15.300.1025.1001
        Status OK

[2016-10-29 19:46:20] [INFO] [ComputeDeviceQueryManager] QueryCPUs START
[2016-10-29 19:46:20] [INFO] [ComputeDeviceQueryManager] QueryCPUs END
[2016-10-29 19:46:20] [INFO] [ComputeDeviceQueryManager] QueryCudaDevices START
[2016-10-29 19:46:21] [INFO] [ComputeDeviceQueryManager] CudaDevicesDetection found no devices. CudaDevicesDetection returned: CUDA error in func 'CudaDetection::QueryDevices' at line 15 : CUDA driver version is insufficient for CUDA runtime version.
[2016-10-29 19:46:21] [INFO] [ComputeDeviceQueryManager] QueryCudaDevices END
[2016-10-29 19:46:21] [INFO] [ComputeDeviceQueryManager] QueryOpenCLDevices START
[2016-10-29 19:46:22] [INFO] [ComputeDeviceQueryManager] AMDOpenCLDeviceDetection found no devices. AMDOpenCLDeviceDetection returned: AMDOpenCLDeviceDetection::QueryDevices() exception: clGetDeviceIDs
[2016-10-29 19:46:22] [INFO] [ComputeDeviceQueryManager] QueryOpenCLDevices END
[2016-10-29 19:46:22] [INFO] [ComputeDeviceQueryManager] QueryAMD START
[2016-10-29 19:46:22] [INFO] [ComputeDeviceQueryManager] Checking AMD device (driver): AMD Radeon HD 7900 Series (15.300.1025.1001)
[2016-10-29 19:46:22] [INFO] [ComputeDeviceQueryManager] Checking AMD device (driver): AMD Radeon HD 7900 Series (15.300.1025.1001)
[2016-10-29 19:46:22] [INFO] [ComputeDeviceQueryManager] Checking AMD device (driver): AMD Radeon (TM) R9 390 Series (15.300.1025.1001)
[2016-10-29 19:46:22] [INFO] [ComputeDeviceQueryManager] Checking AMD device (driver): AMD Radeon (TM) R9 390 Series (15.300.1025.1001)
[2016-10-29 19:46:22] [INFO] [ComputeDeviceQueryManager] QueryAMD END
[2016-10-29 19:46:22] [INFO] [ComputeDeviceQueryManager] Cuda NVIDIA/CUDA device count GOOD
[2016-10-29 19:46:22] [INFO] [ComputeDeviceQueryManager] AMD GPU device count BAD!!!

**Comment by sizhuk** [comment] 2016-10-29 18:17
**jane1e**, what OS are you using? And what model of CPU?
The only platform, on which NHM detects GPUs on the first and any next runs is Intel Celeron 847. But I think normally it shouldn't cause the problem.

**Comment by jane1e** [comment] 2016-10-29 18:26
win 7 / 64, 2x GIGABYTE R795WF3-3GD, 2x GIGABYTE R9 390 G1 WINDFORCE 2X Gaming 8GB . Driver radeon-crimson-15.12-with-dotnet45-win7-64bit . NMH show CPU only.

**Comment by jane1e** [comment] 2016-10-31 08:11
ver 1.6.1.4 detect GPU correctly

**Comment by namtr0** [comment] 2016-11-08 03:33
I have same issue with 6 rx 480's failing to get info after detection:
[2016-11-07 20:14:26] [INFO] [ComputeDeviceQueryManager] AMD GPUs count : 6
[2016-11-07 20:14:26] [INFO] [ComputeDeviceQueryManager] AMD Getting device name and serial from ADL
[2016-11-07 20:14:26] [INFO] [ComputeDeviceQueryManager] Number Of Adapters: 46
[2016-11-07 20:14:26] [INFO] [ComputeDeviceQueryManager] ADL_Adapter_AdapterInfo_Get() returned error code -3
[2016-11-07 20:14:26] [INFO] [ComputeDeviceQueryManager] AMD OpenCL and ADL AMD query COUNTS DIFFERENT/BAD

**Comment by S74nk0** [comment] 2016-11-30 13:28
Closing this issue. [New issue](https://github.com/nicehash/NiceHashMiner/issues/393) will be opened until we push out a new release. The fix will be most likely available with the new upcoming release.

**Closed as completed by S74nk0** 2016-11-30 13:28 UTC

**Comment by krazyjames420** [comment] 2017-03-04 05:47
I have a few issues, 1. Nicehash miner don't detect any graphics on my computers Dell AMD phenom 2 X4 only the cpu's And the second issue is with nicehash 1.7.5.1 is not showing anything to mine on when all the older versions found the cpu. What is a good starter card to use for Selling hashing power? I am looking to use one card to purchases more.   Please help donate so i can get more cards i only have about $50-$100 in cash to get anything 1NHbwfNCMcotGiQgsJtTSzvutgkVmQ17Xy

**Comment by Sawtaytoes** [comment] 2018-01-04 05:02
I've got one AMD Radeon R9 270X not showing up while all my other machines with the exact same hardware are showing that GPU. The only difference is those other two rigs are still on driver version 17.10 whereas this one is on the latest 17.12. Do you think that might have something to do with it?

**Comment by Sawtaytoes** [comment] 2018-01-04 05:42
By going back to the 17.10 driver, I was able to get my AMD R9 270X to show up. Do you know why the latest 17.12 driver doesn't show the card? Does this affect other cards as well in the AMD lineup?

**Comment by chraso** [comment] 2018-01-06 06:23
same here @Sawtaytoes

**Comment by Sawtaytoes** [comment] 2018-01-07 06:34
I had the same issue with an AMD Radeon HD6870. It wasn't showing up on Catalyst 16.2 but worked on 15.12. With that particular card, it makes sense because of its age and the fact that 15.12 was the last official driver release. With the R9 270X, I don't understand why the latest AMD 17.12 driver won't work with NiceHashLegacy.
