### ISSUE TITLE
.Net 4.6.2 incompatibility

### ISSUE THREAD

**Issue by birdie-github** [nicehash/NiceHashMiner-Archived#339] opened 2016-11-09 10:49 UTC
NiceHashMiner is incompatible with .Net 4.6.2: the UI misses all the titles. Please, fix.

**Comment by S74nk0** [comment] 2016-11-28 18:00
This is a minor issue. Please try a new clean version and reopen if the issue is still present. Closing issue.

**Closed as completed by S74nk0** 2016-11-28 18:00 UTC
