### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mauroinagoki** [nicehash/NiceHashMiner-Archived#76] opened 2016-04-10 19:20 UTC
Why my pc is not working?

![nicehashminer_fail](https://cloud.githubusercontent.com/assets/379786/14412295/a8c469f8-ff35-11e5-9cad-cd1fde65cbb5.png)

**Comment by theLosers106** [comment] 2016-04-11 04:40
I am not sure what error you are getting.. A little bit more info about your system would be very helpful in diagnosing your problem.

**Comment by mauroinagoki** [comment] 2016-04-11 13:51
My system is:

CPU: Intel Core i5 4590
GPU: NVIDIA GeForce GTX 970 - https://www.asus.com/br/Graphics-Cards/TURBOGTX970OC4GD5/

I dont understant because when connect other pool like suchpool, it is working. But nicehash is not working

**Comment by theLosers106** [comment] 2016-04-12 15:46
Is it still not working? Some users were experiencing some problem connecting yesterday.

**Comment by mauroinagoki** [comment] 2016-04-12 16:51
Here it is not working since April 4

**Comment by computerchuck** [comment] 2016-04-13 17:24
looks like a possible windows firewall issue.  Have you tried deleting all files, download from website, unpack, benchmark, then pay attention to firewall popup notices.   Make sure your firewall is set to prompt you for new apps.

**Comment by theLosers106** [comment] 2016-04-14 11:38
just for fun, try disabling the neoscrypt algo from running by going to the benchmark window and uncheck it.. see if that solves your problem.. sorry but I am not able to reproduce that same error on my machine so it's kinda hard to tell you why it's happening..

**Comment by mauroinagoki** [comment] 2016-04-15 01:49
I set firewall window off. And i run by going to the benchmark window:

![image](https://cloud.githubusercontent.com/assets/379786/14549037/b53a8004-0292-11e6-9b3a-a47234a83e17.png)

But all not is working!

![image](https://cloud.githubusercontent.com/assets/379786/14549094/194b5b9a-0293-11e6-802b-b0d05c4ae979.png)

Maybe my ip is blocked?

**Comment by mauroinagoki** [comment] 2016-04-15 01:50
And i used location to japan:

![image](https://cloud.githubusercontent.com/assets/379786/14549117/54ff4d18-0293-11e6-8e35-4de11f391dad.png)

**Comment by theLosers106** [comment] 2016-04-15 03:47
Please send your public IP address to support@nicehash.com

**Comment by theLosers106** [comment] 2016-04-15 16:32
and just make sure that you are using your own bitcoin address as some of the default addresses have been unfortunately banned by NiceHash servers as too many connections from different places in the world is connected using the same btc address.. this is their way of dealing with botnets..

**Comment by mauroinagoki** [comment] 2016-04-15 17:43
oh wait...I have a computer that is also by mining and is working. And now I have another computer in onther place that is having this problem. Both use the same bitcoin address...it is problem?

**Comment by mauroinagoki** [comment] 2016-04-15 18:06
uh...i am reading this topic https://bitcointalk.org/index.php?topic=611338.140

My pc1: [addressBTC].worker1 - is working
My pc2: [addressBTC].worker2 - is not working.

When you get home, I'll take a look at the configuration "appendWorkerNames" is false or true

**Comment by theLosers106** [comment] 2016-05-17 16:45
Is this issue resolved?

**Comment by mauroinagoki** [comment] 2016-05-18 01:32
No. Only server Japan is working. I am using version 1.4.0.2

**Comment by nicehashdev** [comment] 2016-06-09 19:18
This issue is not related to NHM, but rather to NiceHash service. All further problems regarding connectivity to NiceHash should be resolved by contacting NiceHash @ support@nicehash.com

**Closed as completed by nicehashdev** 2016-06-09 19:18 UTC
