### ISSUE TITLE
Crossfire cards not detected on 1.7.1.0

### ISSUE THREAD

**Issue by miji** [nicehash/NiceHashMiner-Archived#222] opened 2016-09-15 08:57 UTC
Hi!

I have 2 rigs, one with two 270x and other with two 280x. In both rigs, only one card is detected on 1.7 No problem with 1.6.

Any suggestion?

**Comment by S74nk0** [comment] 2016-09-15 08:59
Hi @miji. Please post the log.txt under logs\log.txt so we can check this issue.

**Comment by Abdulsyukur** [comment] 2016-09-15 09:00
thanks 

```
Pada Kamis, 15 September 2016 15:58, miji <notifications@github.com> menulis:
```

 Hi!I have 2 rigs, one with two 270x and other with two 280x. In both rigs, only one card is detected on 1.7 No problem with 1.6.Any suggestion?—

**Comment by miji** [comment] 2016-09-15 09:04
[log.txt](https://github.com/nicehash/NiceHashMiner/files/474212/log.txt)

**Comment by S74nk0** [comment] 2016-09-15 10:29
Use [NHM v1.7.1.1](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.1.1). This issue should be fixed now. Please report if the problem is resolved.

**Comment by Abdulsyukur** [comment] 2016-09-15 12:05
thanks verymuch 

```
Pada Kamis, 15 September 2016 17:29, Stanko Krstić <notifications@github.com> menulis:
```

 Use NHM v1.7.1.1. This issue should be fixed now. Please report if the problem is resolved.—

**Closed as completed** 2016-09-15 17:34 UTC
