### ISSUE TITLE
0xc00007b error on Windows 7 due to different msvcr120.dll in Bin Folder

### ISSUE THREAD

**Issue by frazier345** [nicehash/NiceHashMiner-Archived#755] opened 2017-03-25 19:17 UTC
msvcr120.dll different from 1.7.5.5 in bin folder (1.7.5.5 is 949K vs 1.7.5.7 was 941k).  Would not run ccminer_cryptonight.exe, Decred, nanashi or neoscrypt on my Windows 7 Computer. Copied over the one from the 1.7.5.5 folder and now they work. 

It was giving a 0xc00007b error. 

worked fine on windows 8.1 pro

**Comment by S74nk0** [comment] 2017-03-25 19:23
@frazier345 This issue happened only on Windows 7 (**Professional**)?

**Comment by althefirst** [comment] 2017-03-25 20:44
yes i too have this issue. right now i have 1.7.5.7 running on 4 single cpu boxes. they are all the same but one box is coming up with this problem, they all are running win 7 pro 64bit sp1 or 2. i just did a windows update on all of then this morning. the unit that is nor working will run 1.7.5.5 ( roll back)
and changing to the msvcr120 .dll has no affect on the unit that is not working with 1.7.5.7

**Comment by frazier345** [comment] 2017-03-26 00:39
Yes on windows 7 Professional.  Windows 8.1 Pro worked fine.  I do not have any windows 10 units.

**Comment by S74nk0** [comment] 2017-03-26 15:43
@frazier345 @althefirst I was checking this issue on a couple of Windows 7 Pro testing rigs all miners work as expected. **But I was able to reproduce it!**  The error is happening due to invalid .dll's. Now all the testing rigs have **Visual C++ Redistributable Packages for Visual Studio 2013** **x86** and **x64** after uninstalling these from the system. With the new version these **.dll's** have been updated and this is probably causing issues. For now download and install [vcredist](https://www.microsoft.com/en-us/download/details.aspx?id=40784) (both versions **vcredist_x64** and **vcredist_x86**) since some ccminers are **x86** and some **x64**. 

Please give feedback if installing [vcredist](https://www.microsoft.com/en-us/download/details.aspx?id=40784) (both **x86** and **x64**) resolves the issue. If it does keep this issue open until it is resolved in a future update.

**Comment by althefirst** [comment] 2017-03-26 17:34
Hi i downloaded both and one thing i did see was the new ver. is 12.00.30005.1 this was on both the version that i downloaded. the ver that was on the CPU box that didn't work was 12.00.25005.1. but was was very odd is the computer's properties said 64 bit. but after installing the 64 bit still had problems. so installed the 32bit(x86) and it came up and asked to repair or remove.  so i did a repair . now have no problems.
i think problem is resolve (maybe)

**Comment by S74nk0** [comment] 2017-03-26 19:04
@althefirst this issue is certainly related to wrong/missing *.dll's, what you have described confirms this.

**Comment by frazier345** [comment] 2017-03-27 15:26
Was able to fix it with your solution after I removed the Visual C++ Redistributable Packages for Visual Studio **2015** x86 and x64. and uninstalled and reinstalled the 2013 versions.  Then they worked.

**Closed as completed** 2017-04-03 10:54 UTC
