### ISSUE TITLE
Reconnecting in 3 seconds

### ISSUE THREAD

**Issue by ChaoticBrady** [nicehash/NiceHashMiner-Archived#298] opened 2016-10-30 04:33 UTC
I decided to give bitcoin mining a shot. I configure it, benchmark and press start. It opens up cmd looking prompt and says lots of stuff like
Connected:
read_until:end of file
Reconnecting in 3 seconds.
This bug/glitch has had me puzzled all day. What exactly do I do?

**Comment by anonymous890890543** [comment] 2016-10-30 11:41
Nicehash Miner v1.7.3.1 same problem here, Algo equihash.
windows 10 64
Graphic card gtx 950
Working great on Cpu mining

**Comment by S74nk0** [comment] 2016-10-30 20:31
@ChaoticBrady, @anonymous890890543 does it loop reconnecting? Try changing location closest to you [Europe, USA, Japan, China]

**Comment by ChaoticBrady** [comment] 2016-10-30 23:14
@S74nk0 Well I have tried that a lot but it never works.

**Comment by nerdatwork** [comment] 2016-10-31 17:56
It is in loop reconnecting and if I start NH again it shows "Nicehash miner needs to connect to internet..."

**Comment by Khairan** [comment] 2016-11-02 20:33
I have the same problem. Strange that yesterday all worked with the same settings, but today "Reconnecting in 3 seconds..." in loop

**Comment by EVGENY1777** [comment] 2016-11-04 14:51
periodic rebooting NiceHashMiner 1
![untitled1](https://cloud.githubusercontent.com/assets/23138776/20009671/6dbe5204-a2b6-11e6-94be-4d509f379ba4.jpg)
.7.3.2
[log.txt](https://github.com/nicehash/NiceHashMiner/files/571785/log.txt)
[General.json.txt](https://github.com/nicehash/NiceHashMiner/files/571798/General.json.txt)

**Comment by EVGENY1777** [comment] 2016-11-04 15:37
the problem is solved new reset miner. server eu too works

**Comment by Khairan** [comment] 2016-11-05 03:39
@EVGENY1777 what is "new reset miner"?

**Comment by EVGENY1777** [comment] 2016-11-05 12:32
Set in new Folder

**Comment by S74nk0** [comment] 2016-11-29 10:55
Closing issue as it seems to be related to NiceHash service downtime and not NiceHash Miner.

**Closed as completed by S74nk0** 2016-11-29 10:55 UTC

**Comment by lutsifer** [comment] 2017-09-01 08:31
It seems this service is down all the time...
