### ISSUE TITLE
[BUG] NHM does not properly detect/crashes 2x 1080s when SLI mode is enabled. 

### ISSUE THREAD

**Issue by mdaria510** [nicehash/NiceHashMiner-Archived#268] opened 2016-10-12 01:13 UTC
With the latest driver/NHM version, whenever SLI is enabled if I start NHM it will give me a notice that my driver version is too old (it isnt), and then the cudadetection.exe process will lock up permanently. It's definitely just a detection issue, if I disable SLI, open NHM and then re-enable SLI, the mining itself works fine.

**Comment by p1r473** [comment] 2017-01-04 19:33
I currently have 1 1080, but want to get 2 1080 TIs in SLI.
A few questions for you:
If you keep SLI disabled, and open NHM, can you still mine both cards?
If you keep SLI disabled, and open NHM, and then re-enable SLI, can you still mine both cards?

Please let me know!

**Comment by S74nk0** [comment] 2017-01-05 11:07
@p1r473 the detection seems to be causing issues with SLI enabled (hopefully this will be fixed soon), mining won't be affected

**Comment by kenshirothefist** [comment] 2017-03-03 21:33
NiceHash Miner has not been tested against SLI configurations. You can try to temporary disable (and disconnect) SLI and see if it works. Closing this as it is a duplicate of https://github.com/nicehash/NiceHashMiner/issues/699

**Closed as completed by kenshirothefist** 2017-03-03 21:33 UTC
Labels: bug
