### ISSUE TITLE
NiceHash Miner 1.7.3.11 | 940M GPU | Cryptonight mining BUG

### ISSUE THREAD

**Issue by ShippyG** [nicehash/NiceHashMiner-Archived#481] opened 2016-12-27 19:41 UTC
When i start mining it tells that my cryptonight mining speed is 34.454 MH/s :D

Screenshot: https://gyazo.com/c9d0f2a321f738c2c89c05d6bbce86fd

**Comment by fefsf** [comment] 2016-12-29 13:52
Its not a bug, you're just becoming a millionaire :)

**Comment by S74nk0** [comment] 2017-01-09 20:46
This is a known bug. Please follow [these](https://github.com/nicehash/NiceHashMiner/issues/500#issuecomment-271076255) instructions and report back on this [issue thread](https://github.com/nicehash/NiceHashMiner/issues/500). closing [duplicate](https://github.com/nicehash/NiceHashMiner/issues/500)

**Closed as completed by S74nk0** 2017-01-09 20:46 UTC
