### ISSUE TITLE
Ethereum mining

### ISSUE THREAD

**Issue by icmos** [nicehash/NiceHashMiner-Archived#49] opened 2016-03-13 18:11 UTC
I try to use my nVidia 750Ti card to mine eth with NiceHashMiner,
the benchmark for eth works fain and give me the result: 8,4 MH/s.
If I start to mine i receive the error:
"cuda error in func 'ethash_cuda_miner::search' at line 288 : unknow error.
x 19:42:43|cudaminer0 Error CUDA mining: unknow error"
I have a free installation of Win 7 64 bit.
Any ideas?

**Comment by mendoza1468** [comment] 2016-03-14 01:35
I think you can't mine with 750ti because it's compute 5.0. You need 5.2 card. (For eth)

**Comment by mendoza1468** [comment] 2016-03-14 01:35
Still the same problem for me on this version (win 10), 32 mh/s precise benchmark for eth but after 5 min, do only 5 to 10 mh/s with 2 gtx970

**Comment by icmos** [comment] 2016-03-14 14:12
I mine with 750Ti using ethminer in Ubuntu even at nicehash.com, so I suppose is some bug in nicehashminer.

**Comment by theLosers106** [comment] 2016-03-15 01:51
I can confirm that for some reason it can't be mine on Windows.. not sure why though.. at least using Genoil's ethminer v1.0.3.. so I'll be closing this..

**Closed as completed by theLosers106** 2016-03-15 01:51 UTC
