### ISSUE TITLE
Equihash (excavator) slower than eqm for GTX1080

### ISSUE THREAD

**Issue by Kingdud** [nicehash/NiceHashMiner-Archived#743] opened 2017-03-21 00:30 UTC
I just updated to 1.7.5.6-pre-release-01b and the new equihash method (excavator) is about 5% slower (475 Sols/s vs 500 Sols/s) than the old EQM miner. I'm using default settings for the miner, I haven't tweaked anything on either EQM or excavator. This result is true for both sustained mining and benchmarking.

**Comment by Joshwaa2010** [comment] 2017-03-21 15:12
I am having the same results kinda.  GTX 1080 ti  642sols on eqm and 620sols on excavator.

**Comment by nicehashdev** [comment] 2017-03-21 21:53
Try running with 3 threads and report back.

**Comment by Kingdud** [comment] 2017-03-21 22:15
3 thread result: 442-454 Sols/s, effectively the same performance as running with a single thread.

**Comment by nicehashdev** [comment] 2017-03-21 23:37
Are you using latests NVIDIA drivers? OS? CPU?

**Comment by Kingdud** [comment] 2017-03-21 23:45
378.66 Nvidia Driver (Installed on 3/3/2017)
Windows 7 64-bit
i7 6700k (not overclocked)

**Comment by nicehashdev** [comment] 2017-03-22 01:17
We have no idea what could be the cause. All the systems with various NVIDIA cards we have do not have the behaviour you are explaining.

We will monitor this for issue and see if we can come up with a cause for this.

**Comment by Joshwaa2010** [comment] 2017-03-22 02:46
I updated the system with the 1080 ti to the drivers that came out a day or two ago and now the new one is slightly faster. But my system with the 1080 I can not get faster on the pre release. Will test more tomorrow and report back.

**Comment by Kingdud** [comment] 2017-03-22 04:01
I just updated to 378.92; no joy, still getting 460-475 Sol/s.

**Comment by fefsf** [comment] 2017-03-22 16:06
a few months ago my 1080 would randomly do Equihash at well over 520 SOL/sec...then sometimes it would do ~460SOL/sec. I could never identify or explain why it would do one vs the other. OC was the same each time too. I think  the 1080 normally does it in the mid maybe upper 400s, and the 500+ is just a fluke for unknown reasons. My 1080 hasnt hit 500+ in several weeks now.

**Comment by nicehashdev** [comment] 2017-03-22 17:54
Make sure that your clocks are high. It can happen, that some apps cause your clocks to be locked low (no boost). Chrome is an example of such application. When this happens, your speed will be low.

We believe that is a driver bug that hasn't been addressed by NVIDIA.

**Comment by kenshirothefist** [comment] 2017-03-26 13:57
@Kingdud @Joshwaa2010 @fefsf Have you tried the latest [release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.7) which includes latest **excavator**? Make sure to reboot your computer/rig and only start NiceHash Miner (no other apps) before you do testing/benchmarking. Please report back.

**Comment by fefsf** [comment] 2017-03-26 14:24
@kenshirothefist yes,the new excavator gets me around 470/sol,a slight improvement vs before. My memory is +500 and core +150 which results in a freq just shy of 2100mhz

**Comment by nicehashdev** [comment] 2017-03-26 15:12
We just tested with our systems, GTX 1080 with your clocks and open TDP gets over 500.

Are you sure you are running 2 threads and not 1? Because speed of 470 is achieved with 1 thread.

**Comment by fefsf** [comment] 2017-03-26 15:16
@nicehashdev I'm using whatever the default settings are for NHM

**Comment by nicehashdev** [comment] 2017-03-26 15:20
You should make sure 2 threads are being launched (check log or paste it here).

**Comment by Joshwaa2010** [comment] 2017-03-26 15:27
What is the correct flag to put in the settings to force 2 threads?

**Comment by fefsf** [comment] 2017-03-26 16:40
[2017-03-26 12:26:50] [INFO] [MiningSession] Current device profits:
	Profits for GPU-c6c72a06-1c12-3c71-2fe6-bf9897b5b70d (GPU#1 MSI GeForce GTX 1080):
		PROFIT = 0.003679221853	(SPEED = 470.922796		| NHSMA = 7812.792)	[excavator_Equihash]
		MOST PROFITABLE ALGO: excavator_Equihash, PROFIT: 0.003679221853


[2017-03-26 12:26:50] [INFO] [MiningSession] Current Global profit: 3.66987663 USD/Day
[2017-03-26 12:26:50] [INFO] [MiningSession] Current Global profit: IS PROFITABLE MinProfit mine always regardless of profit
[2017-03-26 12:26:50] [INFO] [excavator-MINER_ID(0)-DEVICE_IDs(NOT_SET)] NEW MINER CREATED
[2017-03-26 12:26:51] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "" for device UUID GPU-c6c72a06-1c12-3c71-2fe6-bf9897b5b70d
[2017-03-26 12:26:51] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "" for device UUID GPU-c6c72a06-1c12-3c71-2fe6-bf9897b5b70d
[2017-03-26 12:26:51] [INFO] [ExtraLaunchParametersParser] Final extra launch params parse ""
[2017-03-26 12:26:51] [INFO] [ExtraLaunchParametersParser] AMD parsing temperature control parameters
[2017-03-26 12:26:51] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "" for device UUID GPU-c6c72a06-1c12-3c71-2fe6-bf9897b5b70d
[2017-03-26 12:26:51] [INFO] [ExtraLaunchParametersParser] ExtraLaunch params "" for device UUID GPU-c6c72a06-1c12-3c71-2fe6-bf9897b5b70d
[2017-03-26 12:26:51] [INFO] [ExtraLaunchParametersParser] Final extra launch params parse ""
[2017-03-26 12:26:51] [INFO] [excavator-MINER_ID(0)-DEVICE_IDs(0)] Starting miner [pid(3936)|bin(bin\excavator\excavator.exe)]  -cd 0 0     -a equihash -p 4000 -s equihash.usa.nicehash.com:3357 -u BTCADR.WRKR:x
[2017-03-26 12:26:51] [INFO] [excavator-MINER_ID(0)-DEVICE_IDs(0)] [pid(3936)|bin(bin\excavator\excavator.exe)] Starting cooldown checker
[2017-03-26 12:26:57] [INFO] [excavator-MINER_ID(0)-DEVICE_IDs(0)] [pid(3936)|bin(bin\excavator\excavator.exe)] Shutting down miner


Is this launching just one or two threads?

**Comment by Kingdud** [comment] 2017-03-26 17:18
-cd 0 0 <--it should be launching 2 becuase of that, but what you are looking for in the mining window itself is this:
![capture](https://cloud.githubusercontent.com/assets/20249763/24333482/a79fc61c-1226-11e7-8fd7-7d1a1e85ac7a.PNG)

**Comment by fefsf** [comment] 2017-03-26 17:27
![untitled](https://cloud.githubusercontent.com/assets/20034137/24333551/f5175652-1227-11e7-974e-2927035933af.png)

Looks like two threads but 470 max SOL. GPU freq is 2088 mhz. Not sure whats going on with it

**Comment by nicehashdev** [comment] 2017-03-26 17:38
Are you sure there is nothing else running behind? Also, what is your memory clock?

**Comment by fefsf** [comment] 2017-03-26 18:03
![c1](https://cloud.githubusercontent.com/assets/20034137/24333789/8ac047be-122c-11e7-88be-1df3c3242415.PNG)

So i noticed something odd. Before i start mining, my GPU memory clock would reflect the OC in afterburner. See above

Once i put the load on the GPU by starting to mine, the GPU memory clocks auomatically drop anywhere from 450-500MHZ (AB numbers). So what was happening was that with my +500 OC on memory (5500MHZ in AB), once i started to mine the memory would drop to 5005 MHZ which is effectively stock memory clocks. This is why i could never break 470 SOL. 

![c2](https://cloud.githubusercontent.com/assets/20034137/24333809/efd87464-122c-11e7-872a-9f8c1cf32e60.PNG)


I bumped the memory to +650, and when i started mining the memory droped 499MHZ, however, it was still above the 5005MHZ i had before. Now i can hit just over 500 SOL. So weird.

**Comment by fefsf** [comment] 2017-03-26 18:05
and when i reset the OC, starting mining would drop the memory clock way below stock speeds as well. No idea whats going on :)

**Comment by fefsf** [comment] 2017-03-26 18:28
This phenomenon doesnt appear to happen while gaming.  Below is +350 Memory OC
![img_20170326_141122](https://cloud.githubusercontent.com/assets/20034137/24334006/7b0a8f92-1230-11e7-979d-0c45b06bfbe9.jpg)

**Comment by Joshwaa2010** [comment] 2017-03-28 00:11
I just checked and the same thing is happening on mine. Soon as I start mining under nicehash it knocks 500mhz off of my memory.  Windows 10 64 , 378.92 nvidia drivers. It happens with every algo not just Equihash.  This exact same thing is happening on my 1080 ti also.

**Comment by fefsf** [comment] 2017-03-28 00:15
@Joshwaa2010 aw damn, I get my 1080ti tomorrow and I was hoping this wouldn't happen to it as well

**Comment by Kingdud** [comment] 2017-03-28 00:25
@Joshwaa2010 @fefsf For what it's worth, the memory downclock is an artifact of GPU Boost 3.0. This isn't nicehash's fault, it's Nvidia's. Even the partner makers (EVGA/MSI/etc) don't have control over how GPU boost decides to shuffle electricity around.

**Comment by Joshwaa2010** [comment] 2017-03-28 00:38
I an not quite sure about that. I know that if you keep it under 39C and do not get within 5% of your power limit the card should not downclock at all.  Plus during all off my gaming the memory never downclocks only the core.

**Comment by fefsf** [comment] 2017-03-28 00:47
Even at stock clocks mining any algorithm on my rig results in the instant memory downclocking 450-500mhz. Gpu boost shouldn't have anything to do with it. And like Josh said ,this doesn't happen in any game

**Comment by kenshirothefist** [comment] 2017-03-28 06:00
@fefsf please do the following:

- download and extract our EQM miner from this [link](https://www.nicehash.com/tools/eqm_v1.0.4c_Win64.zip)
- reboot the PC
- apply your overclocks
- run EQM (see start.bat script in the download folder) directly from extracted folder (do NOT run NiceHashMiner)

Are you still observing memory downclocking?

**Comment by nicehashdev** [comment] 2017-03-28 08:06
It is known that driver is putting cards into P2 state instead of P0 state when there is CUDA work. Difference between these two states is that P2 state has lower memory clock. Your memory clock will always be lower when doing CUDA work if you compare it to memory clock of a game.

Still, for Pascal cards, the delta overclock you apply to memory is valid for P2 state. So if your memory is clocked eg. 4000 in game and 3800 in CUDA, and you set +200 memory overclock, then you should see 4200 in game and 4000 in CUDA.

**Comment by fefsf** [comment] 2017-03-28 09:10
@nicehashdev Thanks for the information. If this is the whats happening, wouldnt this happen to every nvidia card while mining? It seems to not be the case. There should be no way a GTX 1080 can mine well in excess of 500 SOL/sec because that would require a massive memory OC (Over +700), and that would risk system instability because when its not mining the memory freq is dangerously high. But clearly some GTX 1080s have (which implies no memory downclocking). I had a +650 memory OC and a freq of 2088 and i barely managed 500 before it started to slip below. The system actually froze overnight because of this (i assume the spike in memory freq between algo switches)

@kenshirothefist Yes, i still see the memory downclocking with the stand alone EQM miner.

**Comment by fefsf** [comment] 2017-03-28 15:51
It seems the one 'solution' i found is manually set the P2 state memory speed with nvidia inspector.  I guess those times where my 1080 was hitting 530SOL/sec+ a few months ago meant that for whatever reason it wasnt switching to the P2 state, weird.

**Comment by fefsf** [comment] 2017-03-28 23:23
@Joshwaa2010 So i installed my MSI ARMOR 1080Ti today....+100 core +350 memory....700 SOL/sec and now my 1080 is doing almost 500 SOL with my original overclock that used to net me 460 SOL.....dont get it but im happy  for now :)

**Closed as completed** 2017-04-03 10:57 UTC

**Comment by shelakel** [comment] 2017-06-20 18:30
@fefsf, I have a similar "issue" with GPU Boost being deactivated on my GTX 1070 (GALAF HOF).

The workaround I'm using to force GPU Boost 3 active is to have an instance of Google Chrome running (I keep a blank tab open in Google Chrome) - the Web GL acceleration keeps the GPU boost active.

470 SOL/sec seems very low for a 1080. I'm getting 495  SOL/sec on the 1070 at 72% power/2113 MHz GPU clock/4404 MHz memory - I'm using Zec miner 0.3.3b

**Comment by himonaco** [comment] 2018-02-17 21:17
Try bminer. I get 620 sol with gtx 1080 with no OC
