### ISSUE TITLE
AMD ethminer windows doesnt close on minning new coin (unconfirmed)

### ISSUE THREAD

**Issue by Arganaz** [nicehash/NiceHashMiner-Archived#493] opened 2017-01-03 14:05 UTC
eqm windows will stay opened when switching to new coin, and keep adding windows every time it switches back and forward.

**Comment by S74nk0** [comment] 2017-01-03 14:06
@Arganaz is this when mining CPU? Also post the logs please.

**Comment by Arganaz** [comment] 2017-01-03 14:44
[log.txt](https://github.com/nicehash/NiceHashMiner/files/682414/log.txt)
not sure if it is visible in this log, 
but nicehash was on bin\ethminer.exe and switched to bin_3rdparty\claymore_zcash\ZecMiner64.exe (CORRELTY, it was more profitable) BUT it didnt close the window(process) for the previous bin\ethminer.exe.

i'm not using CPU for mining. hope this makes it clearer.

**Comment by Arganaz** [comment] 2017-01-03 14:45
Sorry for the confusion ;P

**Comment by S74nk0** [comment] 2017-01-03 14:52
@Arganaz **ethminer** being left opened is expected behavior when switching **BUT only one instance should be left opened** so if there are more than one **ethminer** window opened this is a BUG. Looking at the logs it looks like that reading the API on local host is not always working, but everything else looks fine. Confirm that there are more than 2 miner windows opened at the same time to confirm if this is a BUG or a false positive.

**Comment by Arganaz** [comment] 2017-01-03 14:55
THAT is the problem several windows opened. I'll try and catch it and resend the log with it and also do a print screen with it. I guess the this could be closed for now, I'll open again when i get the data. 
Thank you

**Comment by S74nk0** [comment] 2017-01-03 14:59
@Arganaz keep it opened... when the problem occurs post the logs and some screenshots if you can.

**Comment by Arganaz** [comment] 2017-01-04 15:27
It happened again a few minutes ago. Included is the log and a print screen of the windows (I cut out the background)
![crash](https://cloud.githubusercontent.com/assets/4057548/21647463/43b92c20-d292-11e6-980a-40785f9fb161.jpg)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/685050/log.txt)

**Comment by Arganaz** [comment] 2017-01-04 15:29
Its impossible to close the windows I have to reboot to clear them, it then starts to work fine again

**Comment by S74nk0** [comment] 2017-01-05 11:15
@Arganaz 
`Its impossible to close the windows I have to reboot to clear them, it then starts to work fine again`
This looks like to be a driver related issue since the logs aren't showing anything strange.
Try changing increasing 
Settings > Advanced > Miner Restart Delay [ms].
Also when the miner windows get started try to close them manually and report if they can be closed (they will restart after closing)

**Comment by Skymax7** [comment] 2017-02-26 10:46
this happen to me with Nvidia cards and ethminer,  I alreay set Miner Restart Dalay to 5000 but nothing changed. I only must close it manually.

![eth_window](https://cloud.githubusercontent.com/assets/25384176/23339003/10fc775a-fc19-11e6-82a9-f09c0ec670c8.jpg)

**Comment by S74nk0** [comment] 2017-03-01 13:47
**AMD ethminer** is discontinued.
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.

**Closed as completed by S74nk0** 2017-03-01 13:47 UTC
