### ISSUE TITLE
Nicehash Miner change his algoritm (minerpool) after stop and startit.

### ISSUE THREAD

**Issue by boyod** [nicehash/NiceHashMiner-Archived#838] opened 2017-05-01 12:28 UTC
After the Nicehash Miner 1.7.5.9 restartit his algoritm (minerpool) was changing.  Changing on the best but why this not automatic not how its must.

**Comment by S74nk0** [comment] 2017-05-05 15:49
Please use the latest NHM version. NiceHash Miner will automatically switch on to the most profitable algorithm with the accounted threshold (the default is 5%), meaning it will not switch unless the new most profitable algorithm is more then 5% (with the defaults). Try using the latest version and if this problem is present post the log file so we can investigate the error. If the threshold is the reason that NiceHash Miner isn't switching please close this issue...

**Comment by boyod** [comment] 2017-05-07 10:29
1.7.5.9
2.20 usd/d befor stop, after restart 2.32 - 2,34 usd/d. It's biger 5%.

**Comment by S74nk0** [comment] 2017-05-07 17:37
@boyod please post the log file that shows this case to easily examine the issue.

**Comment by boyod** [comment] 2017-05-08 11:57
I did not remember the time of the event. I'll try later.

**Closed as completed** 2017-05-13 13:42 UTC

**Comment by S74nk0** [comment] 2017-05-13 15:34
There is a confirmed BUG. Use [pre-release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.11-pre) until new official release is out.
