### ISSUE TITLE
[Bug] GTX 780 not mining Equihash/mining window issue

### ISSUE THREAD

**Issue by pggion** [nicehash/NiceHashMiner-Archived#354] opened 2016-11-18 14:35 UTC
Hello,
I'm having the problem that NiceHashMiner is not mining using the Graphic Card (GTX 780), it only uses the CPU.
During Benchmarks there isn't any problem, but it never start mining Equihash.
The other issue is that even if I chose to not show the mining window in the lastest version (1.7.3.5), it still appears.
I'm attaching some screenshots of the issues.

Best regards
![equi01](https://cloud.githubusercontent.com/assets/23556340/20433576/037b70f2-ad83-11e6-849f-02919938f067.JPG)
![equi02](https://cloud.githubusercontent.com/assets/23556340/20433577/037b6620-ad83-11e6-8525-e74cfcb96074.JPG)
![equi03](https://cloud.githubusercontent.com/assets/23556340/20433575/03758462-ad83-11e6-9a4f-622856a2fa3d.JPG)
![equi04](https://cloud.githubusercontent.com/assets/23556340/20433574/03751414-ad83-11e6-810a-78c97abb1354.JPG)

**Comment by CreamyG31337** [comment] 2016-11-19 08:45
i think forcing the mining window to show is their temporary workaround for it not mining in the previous version.
if you start nicehash with task scheduler you wont see any windows, maybe this can be a temporary solution for you.

**Comment by pggion** [comment] 2016-11-19 17:12
Thanks for your reply!
But my main problem is that the GTX 780 is not mining. I can live with the mining window.

**Comment by S74nk0** [comment] 2016-11-28 18:11
@pggion try using the latest release. When mining **Equihash** CPU will be using **eqm**, GTX 780 will be using **nheqminer**. Closing issue as it should be fixed in the newer release. Open a new issue if the problem is still present as it may be an issue with **nheqminer**.

**Closed as completed by S74nk0** 2016-11-28 18:11 UTC
