### ISSUE TITLE
Sapphire RX 470 8GB

### ISSUE THREAD

**Issue by artfulfr** [nicehash/NiceHashMiner-Archived#246] opened 2016-09-22 14:22 UTC
I have problem mining with nicehashminer

My Rig

MSI Z170A PRO with 6 PCIE Slot
Sapphire RX 470 8GB (6 pcs)
Intel G4400 
RAM 4GB DDR4 avexir
160GB HDD WD
Windows 7 64bit

First problem is the MSI Z170A PRO, the motherboard only detect 3 RX 470 8GB, the other 3 have code 12 issues. ( i can see 6 vga on device manager but only 3 vga work properly )

Second problem is when i try to mining with just only 1 Sapphire RX 470 8GB using Nicehash miner v.1.7.1.4 
when i want to benchmark the GPU , the computer always freeze ( the mouse and anything else cannot be moved ) so i never succes benchmark the Sapphire RX 470 8GB.

I need some advice please help me
Thanks

**Comment by S74nk0** [comment] 2016-09-22 14:33
Hi @artfulfr. Many users have reported issues with RX 470 cards. I would ask you to try 2 things and report your results:
- 1 try benchmarking only DaggerHashimoto algorithm and report if there are any problems
- 2 try benchmarking all algorithms with 15.7.1 driver installed. This driver is known to be most stable with AMD miners.

Please try and report back what are the results.

As for detection I would ask you for the log file to see where is the problem, if some of the cards are not working properly it might have skipped adding them, but send us the log so we can see what is going on.

**Comment by artfulfr** [comment] 2016-09-22 16:13
Hi @S74nk0 . Thanks for your advice

I try benchmarking only with DaggerHashimoto algorithm and it success. then i start mining and i get 23MH/s. ( Run it on windows 10 ) is this a good news or the right way to do is to benchmarking all the algorithm?

and for your second advice i still download the 15.7.1 amd driver, i will report back to you when i finished install the driver.

As for detection I will give the log file to you tomorrow.

Anyway I really want to thank you for giving me the advice.
I am half happy now because I can see the RX 470 8GB start mining.
Thanks

**Comment by felixbrucker** [comment] 2016-09-22 16:41
regarding the detection of the gpus: i had the same issues with my z170 board, its a board/chipset issue, it wont work with more than 2 or 3 gpus

see #171 for reference

i have then opted for this: http://www.asrock.com/mb/intel/h81%20pro%20btc/
its cheaper and has 6 stable pcie connections, no single problem so far

**Comment by artfulfr** [comment] 2016-09-23 07:07
Hi @S74nk0 
I  Install AMD 15.7.1 and still cannot benchmark all the algorithm 
but it mine well if only benchmark Dagger Hashimoto.

About the detection, If I put 6 vga on motherboard it will detect 3 vga working properly, but when I put 5 vga, only 2 working properly. 
![20160923_084232-1](https://cloud.githubusercontent.com/assets/22372762/18776779/2aaa1252-819e-11e6-8c8c-844df13b03f5.jpg)

I really don't know what to do next, should I give up with this MSI Board.
Because as I know every board that have PCIE can do mining.
6 PCIE slot shoukd detect 6 vga
5 PCIE slot should detect 5 vga

I have Gigabyte MA770-UD3P with 5 PCIE slot, is there somebody mining with this board before?
how much VGA card can install to the motherboard

**Comment by felixbrucker** [comment] 2016-09-23 13:21
as per [this](https://forum.ethereum.org/discussion/comment/12418/#Comment_12418) thread it _should_ work with this mobo, but none confirmed it

**Comment by artfulfr** [comment] 2016-09-25 13:52
MSI Z170A PRO WORK with maximum 4 Sapphire RX 470 8GB.
Getting 92 MH/s 
Just Add the Card one at a time, it works for me. But 4 card only

**Comment by S74nk0** [comment] 2016-09-26 13:59
Hi @artfulfr. Regarding motherboard setups and maximum graphics cards I rather not give any advice since different setups yield different results (The problem could be with the motherboard itself, power supply that is not powerful enough, GPU defects, ... it is really hard to say since there are many variables here, unless someone had the exact same hardware and found a solution). 

Regarding Sapphire RX 470 8GB (this card from this specific vendor seems problematic), and computer freeze when benchmarking other algorithms than DaggerHashimoto it would be helpful to try the following:
- Try running **\bin\sgminer-5-5-0-general\runme.bat** manually and report if there is any crash
- Try **disabling default optimizations** in NHM and try benchmarking
- Copy over the older [sgminer](https://github.com/nicehash/sgminer/releases/download/5.4.0/sgminer-5.4.0-nicehash-39-windows-amd64.zip) to **\bin\sgminer-5-5-0-general\** (this will not have **lbry** support)
- Try [NHM v1.6.1.4](https://github.com/nicehash/NiceHashMiner/releases/download/1.6.1.4/NiceHashMiner_v1.6.1.4.zip) and report if there is an issue

Your feedback will be helpful.

**Comment by S74nk0** [comment] 2016-09-27 13:24
Hi @artfulfr. You can also try this [patch](https://github.com/nicehash/NiceHashMiner/files/495577/NiceHashMiner_exit_patch.zip) and report if other algorithms get benchmakred and if this fixes system freezing/hangs. Copy it in 1.7.1.4 folder and run the binary.

**Comment by undefy** [comment] 2016-10-25 19:57
Here is a driver patch it worked for me but i have older drivers and h97btc mobo. Had a similar problem with running 6 cards.

ftp://dc2.lbr.id.lv:22/6xGPU/6xGPU_mod/6xGPU_mod.txt

**Comment by S74nk0** [comment] 2016-11-28 19:45
Closing issue. All new questions regarding this issue should be discussed [here](https://github.com/nicehash/NiceHashMiner/issues/389) (#389).

**Closed as completed by S74nk0** 2016-11-28 19:45 UTC
