### ISSUE TITLE
Problens when start mining...

### ISSUE THREAD

**Issue by evtnlife** [nicehash/NiceHashMiner-Archived#515] opened 2017-01-15 14:27 UTC
Hello guys, i am trying to miner using nicehashminer, but it every time my speed down to zero at website, this is normaly or is a problem, i made a screenshot, another problem my vga don't start mining with equihash, this is say none at benchmark...

![sem titulo](https://cloud.githubusercontent.com/assets/18296827/21963200/ed89d6f2-db14-11e6-8ae6-592e6fcb0f51.png)

**Comment by AlaskaHobbyMiner** [comment] 2017-01-15 19:14
Hello, here try this,
Switch CPU-1 to mine cryptonight,
and GPU-1 to mine Equihash and Dagger Hashimoto.

Stop the miner, - click on Settings - Devices / Algorithims Tab,
click on CPU#1 - check the box to enable Cryptonight,
click on GPU#1 - check the box to enable Equihash and Dagger Hashimoto,
Save and Close,
Run benchmarks
Start Mining.

Let it run for an hour or so and check the stats, that should do a little better, 
but run the numbers through a profitability calculator with your power cost per kwh, 
where I live, that rig might not be profitable, unless you had free power.

on my rig, when I mine Cryptonight it only makes .35 cents a day, and ads around 100watts to my power usage, so it's not worth it  at .17 per kwh.

so I just mine Equihash and dagger hashimoto on my GPU's
Hope this helps,

**Comment by evtnlife** [comment] 2017-01-15 19:26
thanks for your comment i apreciate this, but i don't have energy costs in my home, but equihash don't start benchmark test in my computer see the screenshot. And about my mining power oscillate until it reaches zero after buir again as in the graph ...

https://www.nicehash.com/index.jsp?utm_source=NHM&p=miners&addr=1AvycfMEWMpMkimoaPGBPYdBAfCsz56ixf

![sem titulo](https://cloud.githubusercontent.com/assets/18296827/21965465/21fd75ae-db3f-11e6-8f6f-f3d922542cb8.png)

**Comment by evtnlife** [comment] 2017-01-15 19:35
Still mining in cryptonight at CPU, and it still zero power at web statistics... when this goes up, no far this goes down again to zero you have same problem?

![sem titulo](https://cloud.githubusercontent.com/assets/18296827/21965510/374aa7a0-db40-11e6-8a37-508ca03fd68f.png)

**Comment by AlaskaHobbyMiner** [comment] 2017-01-15 20:12
No I don't think I have that problem, but I'm not quite sure what you're saying.

Equihash and Dagger hashimoto are currently around 5 times more profitable than Cryptonight.
but only on GPU mining.
with 2 RX480's GPU's I'm mining at 480 sols equihash, for around $2+ a day.
my FX8350 CPU will mine cryptonight at $0.35 a day.

Did you check these settings,
click the settings button on the miner
click Tab Devices/Algorithim
You'll see CPU#1 and GPU#1 listed,
-click on GPU#1 and make sure the equihash and dagger hashimoto boxes are checked

does the equihash benchmark work now?

**Comment by AlaskaHobbyMiner** [comment] 2017-01-15 20:17
before you run the benchmarks,
 Click on your CPU and your GPU and make sure all the boxes are checked for each one.

**Comment by evtnlife** [comment] 2017-01-15 20:23
my gpu don't working at equihash, don't start mining, before i started benchmarks, equihash still at none and N/A
![sem titulo](https://cloud.githubusercontent.com/assets/18296827/21965874/601bcb58-db47-11e6-9800-c52efdd169c3.png)

**Comment by AlaskaHobbyMiner** [comment] 2017-01-15 20:26
close the benchmarks page,
 and open the settings page on the miner

**Comment by evtnlife** [comment] 2017-01-15 20:28
if i try to start checking only equihash, gpu don't start mining

![sem titulo](https://cloud.githubusercontent.com/assets/18296827/21965907/fb02c02c-db47-11e6-834e-1a2d16c7e17c.png)

**Comment by evtnlife** [comment] 2017-01-15 20:35
i setted speed to equihash at settings, but it's giving me 0 sols/s
![sem titulo](https://cloud.githubusercontent.com/assets/18296827/21966005/c76ea738-db49-11e6-81ed-f36511417b16.png)

**Comment by AlaskaHobbyMiner** [comment] 2017-01-15 21:06
Ok, I'm not sure what's going on with that, 
Sorry I couldn't help. I'm new to this as well. 
maybe someone else can chime in here..

**Comment by Johann1982** [comment] 2017-01-16 15:55
@evtnlife Hi 
I think the issue is your GPU is too old to mine anything worth while. Also, your cpu will be to slow to make any money at all. CPU mining is just not worth doing ever, even if you have one of the fastest i7 processors.

https://www.nicehash.com/index.jsp?p=calc
Go to the profitability calculator and check the stats on your GPU. The only thing it can mine is Lbry @ 0.01Gh/s
Upgrade to an RX470 if you want to mine Equihash and Daggerhashimoto.

**Comment by S74nk0** [comment] 2017-03-01 09:59
This doesn't seem to be an issue with NiceHash Miner code itself. Please use [BitcoinTalk forum](https://bitcointalk.org/index.php?topic=1274983) for general discussion and tips on NiceHash Miner usage. Closing this issue now.

**Closed as completed by S74nk0** 2017-03-01 09:59 UTC
