### ISSUE TITLE
Wrong Default Parameters for Equihash (ClaymoreAMD)

### ISSUE THREAD

**Issue by Kimax89** [nicehash/NiceHashMiner-Archived#715] opened 2017-03-10 13:17 UTC
-asm 0 was added to both my R9 280X and my RX 480

Equihash (ClaymoreAMD) performs better with -asm 1

**Comment by S74nk0** [comment] 2017-03-10 14:12
@Kimax89 can you please zip the logs folder and post it here?

**Comment by Kimax89** [comment] 2017-03-11 22:24
i noticed it under the extra parameters under Equihash (ClaymoreAMD) in the settings.

''-asm 0'' is being added when you run a Benchmark with an AMD card under that algorythm.

To replicate the problem:
1. check that ''-asm 0'' isn't added to the extra parameters in the setting menu
2. Run a benchmark with that algorythm
3. Check the settings again and you will notice that ''-asm 0'' has been added to the extra parameters

+ the benchmark ran with the extra parameter and therefore gives a lower hashrate than else possible.

**Comment by Kimax89** [comment] 2017-03-11 22:35
I can see that you allready have changed the way the Benchmark tests wich ASM setting to be used, but i wonder why even bother of setting ASM in the first place.

Claymore ZCash Miner automaticly detect how the card should be set. So there is no need to set ASM at all.

**Comment by S74nk0** [comment] 2017-03-13 08:50
@Kimax89 there are cases when **-asm 1** gives 0 hashes (I don't think the miner detects that). The idea is to test both and use the faster option, but the problem is that **v12.3** breaks this feature (the second benchmark always fails to log, it doesn't work). This will have to be changed somehow as it doesnt work with **v12.3**

**Comment by S74nk0** [comment] 2017-03-16 10:52
@Kimax89 this issue has been [resolved](https://github.com/nicehash/NiceHashMiner/commit/18bd432aa91d5d907d90b74e562728c9badb3b3d). Since the previous version might set **-asm 0** with better performance it is best to do a clean install or remove Extra Lunch Parameters for ClaymoreZec.

Closing issue...

**Closed as completed by S74nk0** 2017-03-16 10:52 UTC
Labels: bug
