### ISSUE TITLE
Ethmimer doesn't work with GTX1070

### ISSUE THREAD

**Issue by Teo99** [nicehash/NiceHashMiner-Archived#735] opened 2017-03-17 11:32 UTC
It stops working (even at benchmark) after a few seconds.

**Comment by kenshirothefist** [comment] 2017-03-17 13:57
Make sure you are not overclocking your GPU. Make sure that you have the file ..\bin\ethminer.exe (it is sometimes removed by Antivirus/Defender).

**Comment by Teo99** [comment] 2017-03-17 14:45
Ethminer doesn't work from Nicehash Miner software. 
But it works fine from command line.

**Comment by fefsf** [comment] 2017-03-17 15:20
i noticed yesterday mine would stop working after several minutes on my 6 GPU 1070 rig. Not sure what is going on. Once DHM messed up it stopped the miner from even switching to another algo

**Comment by kenshirothefist** [comment] 2017-03-17 17:08
Guys, these kind of issues report are not of any use for us. You have to give more details and we also need the logs from \logs directory. If possible, paste logs here or send them to support@nicehash.com

**Comment by Teo99** [comment] 2017-03-17 17:59
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_ 

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

Found suitable CUDA device [GeForce GTX 1070] with 8589934592 bytes of GPU memory
Benchmarking on platform: CUDA
Preparing DAG for block #3362495
Warming up...
  i  16:04:32|cudaminer0  set work; seed: #ff48985a, target: #000000000000
  i  16:04:32|cudaminer0  Initialising miner...
Generating DAG seed ff48985a57d27d8fa945ac9a569c090ff85bf96935ecb96cfeecc47d26902db3
Using device: GeForce GTX 1070 (Compute 6.1) THREADS=128 BLOCKS=8192
Generating DAG for GPU #0
Generate DAG device CUDA#0: 0%
Generate DAG device CUDA#0: 3%
Generate DAG device CUDA#0: 7%
Generate DAG device CUDA#0: 10%
Generate DAG device CUDA#0: 13%
Generate DAG device CUDA#0: 17%
Generate DAG device CUDA#0: 20%
Generate DAG device CUDA#0: 23%
Generate DAG device CUDA#0: 27%
Generate DAG device CUDA#0: 30%
Generate DAG device CUDA#0: 33%
Generate DAG device CUDA#0: 37%
Generate DAG device CUDA#0: 40%
Generate DAG device CUDA#0: 43%
Generate DAG device CUDA#0: 47%
Generate DAG device CUDA#0: 50%
Generate DAG device CUDA#0: 53%
Generate DAG device CUDA#0: 57%
Generate DAG device CUDA#0: 60%
Generate DAG device CUDA#0: 63%
Generate DAG device CUDA#0: 67%
Generate DAG device CUDA#0: 70%
Generate DAG device CUDA#0: 73%
Generate DAG device CUDA#0: 77%
Generate DAG device CUDA#0: 80%
Generate DAG device CUDA#0: 83%
Generate DAG device CUDA#0: 87%
Generate DAG device CUDA#0: 90%
Generate DAG device CUDA#0: 93%
Generate DAG device CUDA#0: 97%
  X  16:04:44|cudaminer0  Exception thrown in Worker thread: bad allocation
Trial 1...

**Comment by kenshirothefist** [comment] 2017-03-17 20:47
So what you're trying to say that if you run manually from command line from **..\NiceHashMiner\bin\ethminer.exe** it works fine for you? And only if you run NiceHash Miner it does not work? What command line are you using to run manually?

**Comment by fefsf** [comment] 2017-03-17 21:39
My issue is for whatever reason when ETHminer starts it forces the CPU to 100% and locks the system up. This isnt captured in the log unfortunatley. It seems if i enable DHM on only 2 (out of 6) of the cards, the system maxes out around 80% for a few moments and settles down. 

I dont remember this happening before, was there some change in ETHminer settings within the last several updates?

**Comment by kenshirothefist** [comment] 2017-03-17 22:23
There were no changes to ethminer in the last several updates. This issue might be related to drivers, but I'm not sure. Just for test you could downgrade to some older driver, like 372.54 ?

**Comment by fefsf** [comment] 2017-03-17 22:34
It shouldnt be the drivers, i just updated them in response to this issue hoping it would solve it. Im going to chalk it up to this being the first time my rig has attempted to mine DHM and this is 'normal' with ETHminer. I have a cheap Celeron G1840 thats just being overloaded when the miner initiates the cards up. My friends 4C/8T Xeon hits 45% for a few seconds when starting 5 cards on DHM, no wonder my system or the miner craps out. Shoulda got an i5 :)

**Comment by Teo99** [comment] 2017-03-18 08:17
The command line is:

ethminer.exe  -U -S daggerhashimoto.eu.nicehash.com:3353 -o <bitcoin.address>

**Comment by nicehashdev** [comment] 2017-03-19 01:24
You absolutely need to have enough RAM or virtual memory if you are running multicard setup. All issues regarding bad allocation, out of memory etc.. are gone if you adjust your virtual memory. On 6 card setup, this needs to be more than 32 GB.

**Comment by kenshirothefist** [comment] 2017-03-19 12:03
Also, try different options here: "Settings > Advanced > Dag Load Mode > dropdown: [singlekeep, single, sequental, parallel]" (default is singlekeep).

**Comment by kenshirothefist** [comment] 2017-03-23 11:38
Are you still having issues while trying the suggestions from the last two comments?

**Comment by Teo99** [comment] 2017-03-23 11:48
I used different Dag Load Modes. 
With sequential and parallel seems stable.
With singlekeep and single just don't work.

**Comment by fefsf** [comment] 2017-03-23 12:33
I was hoping the sequential mode would load one dag at a time but that doesn't look like its the case. CPU still jumps and stays at 100%

**Comment by Junior88** [comment] 2017-03-25 18:39
I also noticed that ethminer is not staying open after switching algos. Instead of staying open in the background and stopping the connection so it wouldn't have to load the DAG again, it closes completely and then when it switches algos back to DHM, it has to load the DAG again.  I have reverted back to 1.7.5.1 on my main miner and will need to do further testing on my dev rig for now. I did notice an increase on the new excavator instead of eqm, but with the latest 1.7.5.7 it seemed to be jumping between algos to often, and between the DAG having to be loaded every time it was cutting into the time that it was actually mining.
I have not tried changing the DAG Load Mode > 16GB RAM > 32GB Virtual. x6 GTX1060 latest nvidia drivers- 378.92- 
Update- I ended up turning off DHM except on 2 cards. System seems stable now, on v1.7.5.7, with 2 cards on DHM and 4 on excavator. Your mileage may vary depending on your cards as well. 
Update2- Crashed after several hours of running fine. It opened multiple ethminer.exe windows and system needed to be restarted. Changed DAG load mode to sequential and testing.

**Comment by kenshirothefist** [comment] 2017-03-28 05:54
@Junior88 what you're observing with closing ethminer and re-launching later after switching to DaggerHashimoto is most probably related to Dag Load Mode - only when this is set to "singlekeep" it will stay in the background.

As far as other issues with ethminer are concerned - unfortunately ethminer is mostly abandoned project, but we're already working on integrating DaggerHashimoto into our **excavator** miner. Until we finish this integration there are only these options for those of you who are having issues with ethminer:

- make sure you have up-to-date GPU drivers;
- try without any over-clocking;
- try different options here: "Settings > Advanced > Dag Load Mode > dropdown: [singlekeep, single, sequental, parallel]" (default is singlekeep);
- you need to have enough RAM or virtual memory if you are running multicard setup; on 6 card setup virtual memory (pagafile) needs to be at least than 32 GB;
- if using singlekeep or single Dag Load Mode you need to have a decent CPU and decently fast RAM because it copies DAG from RAM to GPU-RAM and vice versa.

**Closed as completed by kenshirothefist** 2017-03-28 05:54 UTC

**Comment by Bill48105** [comment] 2017-06-01 05:44
Had this happen with SINGLE 1050 ti & nicehash miner 1.7.5.12 today using latest 382.33 drivers. Was driving me bonkers as nicehash benchmarks for DaggerHashimoto would never finish they'd hang indefinitely until stopped manually. The same card & drivers worked fine on 2 other computers.  Logs were not too useful to understand what was going on so I ran manually using the command line shown in the logs & low & behold that same "cudaminer0  Exception thrown in Worker thread: bad allocation" error which brought me to this  Issue post. **I can confirm on this system with 4GB RAM, the Windows pagefile was set too small at 256MB initial, 1024MB max.** I believe a SSD utility did that to reduce write wear, Increasing to 4096 8192 made the benchmark complete OK & I was able to start mining after 3 hours of fighting with nvidia drivers on this computer over this. I get it's a Windows issue or likely the SSD utility's fault but it exposes a few shortcomings in nicehash miner. It'd be nice if the nicehash miner checked the memory & pagefile as a sanity check. It'd be nice if there was an option to not hide the miner executable during benchmarking to be able to see what's going on.  Maybe the GUI should have a time limit for each test & if timeout show some miner output.  Anyhow I realize this Issue has been closed but I felt it would be helpful to other users who run into this to save them some grief & to the developers to maybe make it more fool proof & user friendly for this particular peculiarity. Thanks
