### ISSUE TITLE
nicehash stats not showing via console link.

### ISSUE THREAD

**Issue by dogfried** [nicehash/NiceHashMiner-Archived#466] opened 2016-12-20 15:14 UTC
Hi,
I have just mangaed to get my 5x rx 470 rig to work on all 5 gpu's today.When it was running on 4 cards the stats for estimated income ect would show up using the link attached to the nicehash miner console.However now i have managed to get the 5th gpu working the link no longer shows the stats for the rig.Also my balance is'nt changing on the console itself either,even though it apears to be mining.
Any ideas?
Below is the mod i used to get the 5th gpu to work.
https://lbr.id.lv/6xgpu_mod/6xGPU_mod.html

**Comment by S74nk0** [comment] 2016-12-20 20:51
Are you running Windows 10? What was the algorithm you were running? There seems to be an issue with the newer AMD drivers on Windows 10 when mining DaggerHashimoto. Are you having issues when mining Equihash?

**Comment by dogfried** [comment] 2016-12-20 20:59
I'm on windows 8.1.i only know how to use nice hash miners main interface and not the individual miners.it is mining daggerhashimoto.

**Comment by S74nk0** [comment] 2016-12-20 21:04
@dogfried there were reports that ethminer the miner used for **daggerhashimoto** is not working correctly on Windows 10 with newer **AMD** drivers. We have seen this in one of the testing machines with Windows 10, Windows 7 works fine, but we didn't test it with Windows 8.1. This could be related to Windows 8.1 as well. What driver version is installed?

**Comment by dogfried** [comment] 2016-12-20 21:10
The driver version is 21.19.384.0.it took quite some time just to get 4 gpu's working.the gpu's are sapphire nitro rx470's

**Comment by S74nk0** [comment] 2016-12-20 21:31
Please try mining only **Equihash** for a while and report back if there is an issue when mining **Equihash** to determine if the issue is with **ethminer/daggerhashimoto ** or hardware setup.

**Comment by dogfried** [comment] 2016-12-20 21:34
Can I do that on the main nice hash miner.i interface?

**Comment by S74nk0** [comment] 2016-12-20 21:39
`Can I do that on the main nice hash miner.i interface?` Yes! Just go to the **Settings > Devices/Algorithms > and disable daggerhashimoto** for every device.
Image as an example:
![example](https://cloud.githubusercontent.com/assets/1517233/21369008/2e0cef4e-c705-11e6-93b4-d88bf1ca240b.PNG)

**Comment by dogfried** [comment] 2016-12-20 21:46
Thank you its done and started.it has solved the check my stats link.its now working.this leaves us with a driver problem then?

**Comment by S74nk0** [comment] 2016-12-20 21:49
Keep it running for a while. But is seems to be related to the driver. Check out [here](https://github.com/nicehash/NiceHashMiner/issues/450) and [here](https://github.com/nicehash/NiceHashMiner/issues/454). 
The 09.11.2016 driver should work

**Comment by S74nk0** [comment] 2017-03-01 10:49
Try using [Pre-Release](https://github.com/nicehash/NiceHashMiner/releases/tag/1.7.5.2-pre).

Closing issue as it is related to an older version of NiceHash Miner.

**Closed as completed by S74nk0** 2017-03-01 10:49 UTC
