### ISSUE TITLE
trying to mine zcash

### ISSUE THREAD

**Issue by plifter** [nicehash/NiceHashMiner-Archived#294] opened 2016-10-29 22:26 UTC
it keeps restarting after 30 accepts on all my graphics cards what is the problem

**Comment by S74nk0** [comment] 2016-10-30 20:43
Hi @plifter. Is this with happening with **v1.7.3.1**?

**Comment by sonicdx10** [comment] 2016-11-01 18:36
Yes, it's happening on the last version x.x.3.1... tested with nvidia

**Comment by MoNTE48** [comment] 2016-11-01 23:41
I get only 15 Sols/s on RX470 8GB with your miner. And 34 Sols/s with Genoil!

**Comment by S74nk0** [comment] 2016-11-02 14:51
@MoNTE48 we are working on a AMD optimized version.
Regarding restarts it would be helpful to give some more information. **nheqminer** is working stable without restarts even with mixed devices (CPU, NVIDIA and AMD combined). So what GPUs are being used and when do the restarts happen?

**Comment by S74nk0** [comment] 2016-11-28 19:37
Closing issue as it is related to old NHM version. Use the latest release and open a new issue if the problem is still present.

**Closed as completed by S74nk0** 2016-11-28 19:37 UTC
