### ISSUE TITLE
Ethereum - Tries to create the dag every time it launches

### ISSUE THREAD

**Issue by JCBauza** [nicehash/NiceHashMiner-Archived#60] opened 2016-03-24 16:42 UTC
Hi,

Everytime I launch the application, it tries to recreate the dag file. When it is about 25% it closes the proxy and miner windows and starts all over again. I manually ran the miner and it did not try to recreate the dag and worked with another proxy I have for mining ethereum. I am currently mining Ethereum as NicehashMiner can't get it to work on my computer. Any ideas as to why are greatly appreciated, thanks!

**Comment by theLosers106** [comment] 2016-03-24 17:24
Hi there @JCBauza ,

Could you check the data folder and see if there is a dag file in there.. btw.. what GPU are you using? AMD? nVidia? or both?

**Comment by JCBauza** [comment] 2016-03-24 17:59
I have two files: full-R23-03b8bc47a10d1baa and full-R23-39238891c3ff3084. I am using an AMD GPU.

**Comment by theLosers106** [comment] 2016-03-25 02:49
There should be a folder called AMD_OpenCL .. does both of the files exists in that folder?

**Comment by CreamyG31337** [comment] 2016-03-25 21:25
Is that what these 3 1.30 GB files are? Please try harder to clean up this type of stuff.

**Comment by JCBauza** [comment] 2016-03-26 23:48
Yup, they exist on the subfolder as well.

**Comment by adamwestland** [comment] 2016-03-27 01:05
@JCBauza 

Try changing the value for EthMinerGraceAPI in the setting from 2 minutes to something like 10 or 20 minutes.  I think this value tells the miner how long to wait without submitting a share before restarting itself.  If a share is found and submitted before the timer hits 0, then it will reset back to the default value but the initial dag creation can take longer than that.

**Comment by theLosers106** [comment] 2016-03-29 07:51
did @adamwestland solution fixed ur problem, @JCBauza ?

**Comment by apprehensivemom** [comment] 2016-04-01 08:23
I had same problem with nvidia 970 and intel3770k 16GB.
 miner was restarting every few minutes creating dag
but when I changed EthMinerGraceAPI from 2 to 22 miner finally started producing money

Same problem with nvidia 960 amd intel6700k 32GB ram with "creating dag".
Solved changing EthMinerGraceAPI to 22 even if waiting time was very long (due to RAM?)
When finally miner run, after little time program was stuck.
Stopping and restarting helped. Now it is OK
Here is the screen capture when it was stuck. Both ether-proxy and ethminer.
Maybe the cause was a corrupt DAG?

![immagine](https://cloud.githubusercontent.com/assets/16473762/14201499/ba22ce96-f7f2-11e5-93d1-7b5b50140c5a.jpg)

**Comment by apprehensivemom** [comment] 2016-04-02 08:15
I had another (little) problem with ethereum or maybe just a question:
I enabled the debug window and I got this   "[NVIDIA5x] warning"   message..
warning WHY? overheat? can't get money? what is happening?
![warn](https://cloud.githubusercontent.com/assets/16473762/14225202/6cac0420-f8ba-11e5-93bc-1f92e4c253cb.jpg)
I have noticed that when this message changes from WARNING! to ERROR! both the programs restart (eth-proxy and ethminer) an then the message is
NumRetries:263
NumRetries:262
...261....260 until 230 then again
Ethminer WARNING!  then ERROR..... then restart.

**Comment by theLosers106** [comment] 2016-04-02 10:15
@apprehensivemom 
- for the first problem about the stuck I am not sure about that.. did you change anything like mem clock or core clock? that might cause it to get stuck other than corrupt DAG file.. but again.. I'm just guessing here.. not sure why.. does it happen all the time? try deleting the data directory and see if the same problem persist..
- for the second problem, you would for now have to go to the bin\ethereum directory and edit the file config.json .. look for clientTimeout and change that from say 5m (5 minutes) to 10m (10 minutes) or higher..

**Comment by apprehensivemom** [comment] 2016-04-09 16:58
first problem: you were right, i played a bit with ASUS GPU TWEAK
second problem: yes, much better with longer timeout

**Comment by theLosers106** [comment] 2016-05-17 16:44
This issue is resolved in the latest version..

**Closed as completed by theLosers106** 2016-05-17 16:44 UTC
