### ISSUE TITLE
Won't start CPU and Equihash (only), fails benchmark and won't bypass test 

### ISSUE THREAD

**Issue by DaaBoss** [nicehash/NiceHashMiner-Archived#304] opened 2016-11-02 14:46 UTC
I suspect that some CPUs are not properly recognized, since this works on most of my PCs.  They are all fully patched, malware free PCs of many types.  NOTE that other algorithms DO work and pass benchmarks and do start mining, so this is isolated to Equihash.

However, I have two different PCs, and neither of them will start, getting the same error, when Equihash only was chosen, CPU only.  It fails when trying to benchmark every time, no matter what.  Reinstalling doesn't help.  Also, if you try to bypass benchmark, it THEN tells you that you haven't chosen a device.  To ensure that it is not a settings issue, most everything is set to default, then tried this:  
- Only CPU and Equihash chosen/checked.  
- Verified these were the settings in the config files.  
- Close the EXE and reopen.  
- Everything is checked properly, and it still says there is no device chosen when starting to mine, when doing or bypassing benchmark.

I suspect this is a bug that begins with not properly recognizing the CPU make and model, and then failing the benchmark tests as a result.   Further, the "bypass the benchmark tests" feature also fails to start the miner, giving a false error that no device was chosen, (when really, no benchmark was passed).  Giving up unless someone can solve this for these two PCs.

**Comment by S74nk0** [comment] 2016-11-02 15:00
Hi @DaaBoss. 
`I suspect that some CPUs are not properly recognized` why do you suspect this? Is NHM reporting wrong CPUs? 

`Also, if you try to bypass benchmark, it THEN tells you that you haven't chosen a device.` What do you mean by this? If there are no benchmarks or manually entered speeds NHM cannot calculate best profitability.

If you can send the configs and log directory or just logs so we can see what could be wrong.

**Comment by DaaBoss** [comment] 2016-11-02 17:33
CPU type -- just a guess, since it appears that part of the purpose was to possibly adjust certain parameters for some algorithms, and maybe some features required for Equihash were assumed, but not present.  the other evidence is that, most other PCs, fast and slow, seem to work just fine.

Benchmarks -- Seems it should start, with or without them, if the only function is to determine how much it will make.  If it starts mining, then you can see very quickly how much it is making now.  However, I suspect the test does much more, in setting up the config for that device and algorithm, yes?

With both CPU and Equihash ONLY chosen, and I hit start.  First, it says I haven't run benchmarks. THEN:
**-- Tried YES, (RUN benchmark** on Equihash on CPU only) and always returns with the error that it couldn't complete the test, after an extended 4-5 minutes of 100% CPU usage, so I could see that the test was attempted.  After the test and error, If you choose skip instead of retry, (which retry also fails 100% of the time), it then will say, (I can reconfirm later if helpful), in the next message, that I must choose a device or it can't mine.  So it fails to start.  If I try to hit start again, it offers to run the test again for the chosen CPU and Equihash, which I know will fail.

**-- Tried NO, (SKIP** benchmark on Equihash on CPU only), and start mining.  Next, it says I must choose a device or it can't mine, yet, one is always chosen.

I'm attaching both files from config and the log file from one PC. (I can also get the other PC at a later time, if helpful.)  
-- I added notes inside the log file --- and may have found a clue in the log file:  I JUST noticed --- there does NOT seem to be ANY tests run using the CPU, only the GPU !!   (GPU choice was NOT available in the UI--nothing to even check for any algorithm on this PC).

[benchmark_GEN-0e50f9143af164fc1bc027042285aa635b4c350f7fbf9ec65dcc49c185141703 - Copy.json.TXT](https://github.com/nicehash/NiceHashMiner/files/567275/benchmark_GEN-0e50f9143af164fc1bc027042285aa635b4c350f7fbf9ec65dcc49c185141703.-.Copy.json.TXT)
[General - Copy.json.TXT](https://github.com/nicehash/NiceHashMiner/files/567276/General.-.Copy.json.TXT)
[log.txt](https://github.com/nicehash/NiceHashMiner/files/567278/log.txt)

**Comment by S74nk0** [comment] 2016-11-03 07:45
Hi @DaaBoss. I have checked the files. The issue is simple. The benchmarks timeout meaning it always stops before it actually finishes benchmarking. This will be fixed in the new version. To workaround this if you want to mine ZCash only now just write a value higher than 0 in the settings and it will work.

**Comment by DaaBoss** [comment] 2016-11-03 17:03
WOW!  That was simple.  Works... but I'm sure underwhelmed with the speed of a Pentium dual core VS i5 dual core -- No wonder it timed out.  When is is working, it's only 1.2 Sol, vs the i5 is about 4 Sol.  Still the fix is required --- OR, an simple addition to a README would do almost as well, since the only people that will see it, will have PCs that are barely worth making it work.

ONE more question --- when the GPU's firmware is out of date, and you update the firmware, who do you coax it to recognize and add that hardware?  I have a quad CPU Alienware with a huge GPU I probably need to update and put to work, as well as the CPU @ 24 Sol.

Thanks for the fix though!   I think I now owe you a piece of my future earnings on my Pentium....  Lets see...  $.20 /day less elect... hmmm.. :)    Still, I hate unsolved problems, so that did make it worthwhile to fix.

**Comment by S74nk0** [comment] 2016-11-04 00:50
The timeout is increased now to 5 minutes so it will be fixed with a new release

**Closed as completed by S74nk0** 2016-11-04 00:50 UTC

**Comment by wildcat2020** [comment] 2016-11-04 13:23
I seem to have the same problem. 
could you kindly suggest in which setting exactly you need to put a non-zero value?
