### ISSUE TITLE
Miner freezes at start when multiple GPU

### ISSUE THREAD

**Issue by Sapfon** [nicehash/NiceHashMiner-Archived#282] opened 2016-10-26 12:28 UTC
Hello there,

Here is my issue: I'm running following rigs:

H81 pro BTC
8GB of DDR 3
Intel Celeron G1840
5xZotac 750ti 2GB cards with riser cables
Chieftec 650W modular PSU

Windows 8.1 with the newest Nvidia drivers and the newest Nicehash miner.

Benchmark etc goes fine but when I start more than 1 card to mine everything freezes. It happens right after it says pool difficulty set 10 000 and stratum... 

When I launch just one card everything is fine. I suspected power issue but 650W should be more than enough.

**Comment by S74nk0** [comment] 2016-11-29 11:57
@Sapfon what algorithms freeze? Try gradually adding GPUs starting from 1 then 2, ... etc...

**Comment by S74nk0** [comment] 2016-12-02 15:35
Closing issue as it is related to an old version of NiceHash Miner. If the issue is present in the new release open a new issue.

**Closed as completed by S74nk0** 2016-12-02 15:35 UTC
